export const ADD_VACCINATION = 'ADD_VACCINATION';
export const ADD_VACCINATION_SUCCESS = 'ADD_VACCINATION_SUCCESS';
export const SWITCH_TO_CHOOSE_VACCINE = 'SWITCH_TO_CHOOSE_VACCINE';
export const SWITCH_TO_CHOOSE_DATE = 'SWITCH_TO_CHOOSE_DATE';
export const PICK_VACCINE = 'PICK_VACCINE';
export const FETCH_VACCINATIONS = 'FETCH_VACCINATIONS';
export const RECEIVE_VACCINATIONS = 'RECEIVE_VACCINATIONS';
