export const ADD_VACCINATION = 'ADD_VACCINATION';
export const REMOVE_VACCINATION = 'REMOVE_VACCINATION';
export const SWITCH_TO_CHOOSE_VACCINE = 'SWITCH_TO_CHOOSE_VACCINE';
export const SWITCH_TO_CHOOSE_DATE = 'SWITCH_TO_CHOOSE_DATE';
export const PICK_VACCINE = 'PICK_VACCINE';
